name: Build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '13', '17' ]
    name: Java ${{ matrix.Java }} Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/jar