name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      system:
        description: 'System'     
        required: false
        default: 'ubuntu-latest' 
        type: choice
        options:
        - macos-latest
        - windows-latest
        - ubuntu-latest
    
jobs:
  build:
    runs-on: ${{ github.event.inputs.system }}
    strategy:
      matrix:
        java: [ '13', '17' ]
    name: Java ${{ matrix.Java }} Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - run: ant build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ./