name: Build

on:
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '13', '17' ]
    name: Java ${{ matrix.Java }} Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - run: java -version