name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '15', '17' , '18' ]
    name: Java ${{ matrix.Java }} Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - run: ant build -Dversion="${{ github.event.inputs.version }}"
      - run: mv stealbomber.jar stealbomber${{ github.event.inputs.version }}-java${{ matrix.Java }}.jar
      - uses: actions/upload-artifact@v3
        with:
          name: stealbomber${{ github.event.inputs.version }}
          path: ./*.jar